# Generated by Django 4.1.7 on 2023-09-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_left', models.IntegerField(default=90)),
                ('time_start', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=20)),
            ],
        ),
    ]
